services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: anotherknowledgebase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/infrastructure/db/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - anotherknowledgebase-network

  anotherknowledgebase:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_USER: postgres
      DB_PASSWORD: postgres_password
      DB_NAME: anotherknowledgebase
      DB_PORT: 5432
      DB_HOST: postgres
      JWT_SECRET: sss
    networks:
      - anotherknowledgebase-network

networks:
  anotherknowledgebase-network:
    name: anotherknowledgebase-network
    driver: bridge
volumes:
  postgres-data: